language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version

  - echo "==> Build with Docker ..."

  - docker build -f tests/Dockerfile.ubuntu1404 -t php7:ubuntu1404 . | tee tests/output.ubuntu14.04.log
  #- docker build -f tests/Dockerfile.debian7    -t php7-debian7    . | tee tests/output.debian7.log
  - docker build -f tests/Dockerfile.debian8    -t php7:debian8    . | tee tests/output.debian8.log
  - docker build -f tests/Dockerfile.centos6    -t php7:centos6    . | tee tests/output.centos6.log

script:
  - echo "==> Run Test case ..."

  - grep '00:00:00 php-fpm7.0' tests/output.ubuntu14.04.log
  #- grep '00:00:00 php-fpm7.0' tests/output.debian7.log
  - grep '00:00:00 php-fpm7.0' tests/output.debian8.log
  - grep '00:00:00 php-fpm'    tests/output.centos6.log

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  hipchat:
    secure: "DTnXg490xbC3HB3Qs/8aSDSRlrVUBWrDzywuo6+PJrTrQFZbAbn1Xeey9wmibkIB6AigZew+EeBTcmIkactb6zH8cTwOBAaZIAiU2SgMjCBkMXOPblvCd9DToL8ul5/jkwu8ZfV91ncrujczajZDPA1qaKhU3LKqpCVCHIxptRyX2FRsiGS1/2IJSWM/GdVWHzRr4OdYcLixqPlC40iQf6sDlCJAlGmkNSGyMDJ9nOlPKH0fRXW+DBSUMcbYFYO7v3AfDlBibWcaCohhVfaMeYt0BGuQ0cDaxMPPqJbvBySHB04OGFbjFCnQgQe9Q/e7SlUctoKumzloIwcoJOnKtZpHuayXYegRSbUuvVhm0E2a3OHjeuenKdjddF1lOAuUyBal3Jlqy1yIwLafW6lCNaR2+xyJ/tcL2Ds/SSTFnvzxZH1j43acJ59mkFjrA6TQUt81sOG4nlFjHOoD+DriCY1tc6WVP3IltjZUyQBvOrg08DtnTHCJYMG6Yep9hg9y4WO7Hi/3eWiA4z8vYNzOBOz2xVKlqyWTTELwSp04PsnZHxmRInoXdPYK0Jmyh3qNtslcw4l5oHb0htFwyqCPBWbjb0wm/5OrIVcnFXYt9k3/uDOCzz9QsPhulg5Ei+159gNMn4w9djzLVK4IUkzBf/X4PwwH7h56WccHsCGchsc="

