#!/usr/bin/env ansible-playbook
## vim:ft=ansible :

---

# Debian & Ubuntu.
- stat: path=/etc/php/7.1/fpm/php.ini
  register: phpfpm_ubuntu

- include: php-fpm-ubuntu.yml
  when: phpfpm_ubuntu.stat.exists

- stat: path=/etc/php/7.1/cli/php.ini
  register: phpcli_ubuntu

- include: php-cli-ubuntu.yml
  when: phpcli_ubuntu.stat.exists

# CentOS
- stat: path=/etc/php-fpm.conf
  register: phpfpm_centos

- include: php-fpm-centos.yml
  when: phpfpm_centos.stat.exists

