#!/usr/bin/env ansible-playbook
## vim:ft=ansible :

---

- name: install libselinux-python binary for Ansible to work
  yum: name=libselinux-python state=present
  when: ansible_pkg_mgr == "yum"

#- name: delegate to SELINUX handling subtask, if necessary
#  include: set-selinux.yml
#  when: php_in_selinux is defined and php_in_selinux == true

- name: delegate to APT system for installation
  include: use-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: delegate to YUM system for installation
  include: use-yum.yml
  when: ansible_pkg_mgr == "yum"

- include: configure.yml

